include:
  - volumes.yml
services:
  database:
    image: mariadb:13.0.1-rc
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-password}
      MARIADB_DATABASE: ${DATABASE:-database}
      MARIADB_USER: ${DATABASE_USERNAME:-user}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD:-password}
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: database
        target: /var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 2
      start_period: 10s
